@domain = http://localhost:3000
###User Create
POST {{domain}}/users/
Content-Type: application/json

{
  "name": "throwaway",
  "email": "throw@gmail.com",
  "password": "password",
  "password_confirmation": "password",
  "profile_image": "delete_me.jpg"
}

###User Show
GET {{domain}}/users/1

###User Update
PATCH {{domain}}/users/4
Content-Type: application/json

{
  "classification": "artist"
}

###User Destroy
DELETE {{domain}}/users/5