@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDYyNDM4NTV9.ntAM08p_A02IX-W8cPH_rajkLD-TnYTlu9W1nlK4xlo

###sessions create

POST {{domain}}/sessions
Content-Type: application/json

{
  "email": "laura@gmail.com",
  "password": "password"
}

###User Create
POST {{domain}}/users
Content-Type: application/json

{
  "name": "jack",
  "email": "jack@gmail.com",
  "password": "password",
  "password_confirmation": "password",
  "profile_image": "jack.jpg"
}

###User Show
GET {{domain}}/users/1

###User Update
PATCH {{domain}}/users/me
Content-Type: application/json

{
  "tattoo_id": 1
}

###User Destroy
DELETE {{domain}}/users/5

###TATTOOS####################

###TATTOO CREATE
POST {{domain}}/tattoos/
Content-Type: application/json

{
  "price": "700.00",
  "time": "7:00"
}

###TATTOO SHOW
GET {{domain}}/tattoos/1

###TATTOO UPDATE
PATCH {{domain}}/tattoos/4
Content-Type: application/json

{
  "user_id": 1
}

###TATTOO DESTROY
DELETE {{domain}}/tattoos/5

###IMAGES#######################################

###IMAGE CREATE
POST {{domain}}/images
Content-Type: application/json

{
  "url": "https://images.pexels.com/photos/4125687/pexels-photo-4125687.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
}

###IMAGE SHOW
GET {{domain}}/images/1

###IMAGE DESTROY
DELETE {{domain}}/images/4

###RELATIONSHIPS##############################

###RELATIONSHIPS CREATE
POST {{domain}}/relationships/
Content-Type: application/json

{
  "artist_id": 4,
  "client_id": 1
}